version: '3'
services:
  dns:
    build: .
    privileged: true
    depends_on:
      - nginx
    environment:
      - NGINX_NAME=nginx
      - NGINX_HOST=lxc02.z2442
    ports:
      - 127.0.0.1:53:53/tcp
      - 127.0.0.1:53:53/udp
  nginx:
    image: nginx
    volumes:
      - ./assets/nginx/:/tmp/nginx/
      - ./html/:/var/www/
    command: /bin/bash -c "sed 's|NGINX_HOST|lxc02.z2442|g' < /tmp/nginx/site.template > /etc/nginx/conf.d/site.conf && rm /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
